export const CREATE_STORY = "CREATE_STORY"
export const GET_STORYS = "GET_STORYS"
export const GET_STORY = "GET_STORY"
export const IS_LOADING = "IS_LOADING"
export const UPDATE_STORY = "UPDATE_STORY"
export const DELETE_STORY = "DELETE_STORY"